---
title: "Gov 50 Final Project"
author: "Brit Shrader"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the Prison Industrial Complex or Harvard's endowment. For the Prison Industrial Complex, I'm interested in exploring the relationship between de-institutionalization of disabled folks and the rise of the prisons. For Harvard's endowment, I am particularly interested in descriptive statistics, so I would still need to find questions that could be answered with regression. 

## Project proposal and data 

Does incarceration act as an alternative to welfare or, alternatively, does increased welfare decrease incarceration? In this study, I plan to examine the extent to which periods of increased incarceration rates are associated with decreased welfare spending per capita. I hypothesize that incarceration rates increase during periods of decreased welfare spending, with both increased welfare spending decreasing poverty-associated criminalized acts and decreased welfare spending increasing state reliance on incarceration to address poverty. Therefore, during periods of increased welfare spending per capita, I expect that incarceration rates will decrease. During periods of decreased welfare spending per capita, I expect that incarceration rates will increase. My sample is comprised of state level incarceration and welfare spending per capita from 1999-2006. My unit of analysis is the year (e.g., 1999). The explanatory variable of interest is welfare spending per capita. The variable is coded as a number representing the dollar amount spent on welfare per capita. For instance, if the variable were coded as 50, that would mean the state government spent 50 dollars per person on welfare. For a given year, the welfare spending per capita is recorded in the Correlates of State Policy Project database. My outcome variable is the number of incarcerated people in a state per 100,000 people. For instance, if the variable were coded 50, that would mean for every 100,000 people in that state, 50 were incarcerated. For a given year, the number of inmates in a state is recorded in the National Prisoner Statistics database and the total population of a state is recorded in the Census. If I observe increased incarceration rates during years with decreased welfare spending per capita, this will support my hypothesis. However, if I observe decreased incarceration rates during years with decreased welfare spending per capita, this will provide evidence against my hypothesis. When I run my regression of the incarceration rate on the welfare spending per capita variable, a negative, significant coefficient would indicate support for my hypothesis. 
