---
title: "unused code"
author: "Brit Shrader"
date: "2022-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Under custody


```{r}
total_data |>
  ggplot(aes(x = year,
             y = CUSTOTT)) +
  geom_line(aes(group = st)) +
  labs(x = "Year",
       y = "Total inmates under custody",
       title = "Total inmates under custody by state, 1999-2019") +
  xlim(1978, 1982)

total_data |>
  ggplot(aes(x = year,
             y = CWPRIVM + CWPRIVF)) +
  geom_line(aes(group = st)) +
  labs(x = "Year",
       y = "Total inmates under custody",
       title = "Total inmates under custody by state, 1999-2019") +
  xlim(1999, 2019)
```

```{r}
total_data |>
  ggplot(aes(x = year,
             y = ssitotal)) +
  geom_line(aes(group = st)) +
  geom_smooth(size = 2) +
  labs(x = "Year",
       y = "Total Spent on SSI",
       title = "Total Spent on SSI by year and state") +
  xlim(1980, 2011)
```

```{r}
welfare_cap_admit_1990 <- lm((ADTOTM + ADTOTF) ~ welfare_spending_percap + year, data = total_data, subset = (year < 1990) & (st == "CA")) 
welfare_cap_admit_1990
```

```{r}
## welfare spending per cap vs admission

lm_welfare_cap <- lm((ADTOTM + ADTOTF) ~ welfare_spending_percap, data = total_data) 

lm_welfare_cap |>
broom::tidy() |> select(term, estimate) |> knitr::kable(digits = 2)

lm_welfare_cap_year <- lm((ADTOTM + ADTOTF) ~ welfare_spending_percap + year, data = total_data)

welfare_cap_admit_year |>
broom::tidy() |> select(term, estimate) |> knitr::kable(digits = 2)

```

